// swift-tools-version: 5.7

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription

let package = Package(
    name: "Relying Party Server",
    platforms: [
        .macOS("12.0")
    ],
    products: [
        .executable(
            name: "RelyingPartyServer",
            targets: ["RelyingPartyServer"]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/vapor/vapor.git", "4.0.0"..<"5.0.0")
    ],
    targets: [
        .executableTarget(
            name: "RelyingPartyServer",
            dependencies: [
                .product(name: "Vapor", package: "vapor")
            ]
        ),
        .testTarget(
            name: "RelyingPartyServerTests",
            dependencies: [
                .target(name: "RelyingPartyServer"),
                .product(name: "XCTVapor", package: "vapor")
            ]
        )
    ]
)
